
#[SECRET]
#1_boot-admin-server_[Secret].yml

apiVersion: v1
kind: Secret
metadata:
  name: boot-admin-server-secret
  namespace: default
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=

