
#[CONFIGMAP-SECRET]
#1_boot-admin-server_[ConfigMap-Secret].yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-admin-server
  namespace: default
  labels:
    app: microservicio-boot-admin-server
    role: backend
    stage: production
    version: v1.0.0
data:
  #-------------------------------------------------------------------#
  #--------------- CONFIGURACION PROPERTIES [utl-capadb] -------------#
  #-------------------------------------------------------------------# 
  application.properties: |-
    grupoconfig01.nombres=CESAR GUERRA
    grupoconfig01.dni=41816133
    propiedades.config.valor_01=JAVAMAN
    propiedades.config.valor_02=MAKTUP

    #'BOOT-ADMIN' configuracion:
    management.endpoints.web.base-path=/
    spring.boot.admin.ui.title=ADMINISTRACION BOOT-ADMIN
    
    # TRUE  ==> ESCENARIO 'SI SEGURO'
    # FALSE ==> ESCENARIO 'NO SEGURO'
    spring.boot.admin.security.enabled=false
    
    spring.security.user.name=${BOOTADMIN_USUARIO}
    spring.security.user.password=${BOOTADMIN_PASSWORD}
     
    #'BOOT-ADMIN' proyectos NO consierados (FILTRADOS):
    spring.boot.admin.discovery.ignored-services=${SERVICIOS_IGNORADOS}
    
    #Configuracion de 'KUBERNETES':
    spring.cloud.kubernetes.discovery.all-namespaces=true
    spring.cloud.kubernetes.discovery.catalog-services-watch.enabled=false
    
    #ELASTICSEARCH [LOGs], NO configurado para que se le lean sus LOGs. 
    logging.pattern.console=[%-5level] [%d{dd-MM-yyyy HH:mm:ss.SSS}] [%thread] | %msg%n

---

#[SECRET]
#1_boot-admin-server_[Secret].yml

apiVersion: v1
kind: Secret
metadata:
  name: boot-admin-server-secret
  namespace: default
  labels:
    app: microservicio-boot-admin-server
    role: backend
    stage: production
    version: v1.0.0
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=

