
#[SERVICE]
#3_boot-admin-server_[Service].yml

apiVersion: v1
kind: Service
metadata:
  name: boot-admin-server
  namespace: default
  labels:
    app: microservicio-boot-admin-server
    role: backend
    stage: production
spec: 
  ports:
    - name: http
      port: 8080
  selector:
    app: microservicio-boot-admin-server
    version: v1.0.0
  type: NodePort
